Fix empty prefix in pin attributes for transport lines with empty prefix
th2-net/th2-codec-sailfish pull request #192
Opened 2023-09-21 12:30 UTC by OptimumCode

2023-09-22 07:21 UTC, Nikita-Smirnov-Exactpro requested changes

2023-09-22 07:21 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/Application.kt
> +            val duplicates = configuration.transportLines.keys - trimmedPrefixes
We should use another approach to find duplicates, because the current approach shows "a  " as duplicate in the source set {"a  "}

2023-09-22 07:52 UTC, OptimumCode commented on src/main/kotlin/com/exactpro/th2/codec/Application.kt
> +            val duplicates = configuration.transportLines.keys - trimmedPrefixes
Does it? We compare the sizes of the trimmed set and the original set. So, if we had `["a "]` we will have `["a"]` and the size will be equal.
If you are talking about the error message then maybe yes, the error will contain `"a "` as a duplicate. But maybe we just need to correct the error. Something like: transport lines have untrimmed names and have duplicates after names is trimmed

2023-09-25 08:33 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/Application.kt
> +            val duplicates = configuration.transportLines.keys - trimmedPrefixes
Thanks for answer, let's correct error message

2023-09-26 10:04 UTC, Nikita-Smirnov-Exactpro approved these changes

2023-09-26 12:54 UTC, merged