[TH2-1766] Add notifier about error during decode message
th2-net/th2-codec-sailfish pull request #26
Opened 2021-05-20 12:51 UTC by IvanChadin

2021-06-02 11:08 UTC, jean-michel-perli-sonsin commented on README.md
> +Schema API allows the configuration of messages routing streams via links between connections and filters on pins.
```suggestion
Schema API allows the configuration of routing streams messages via links between connections and filters on pins.
```

2021-06-02 11:10 UTC, jean-michel-perli-sonsin commented on README.md
>  You can declare multiple pins with attributes `['decoder_out', 'parsed', 'publish']` and filters instead of common pin or in addition to it.
```suggestion
You can declare multiple pins with the attributes `['decoder_out', 'parsed', 'publish']` and filters, instead of a common pin or in addition to it.
```

2021-06-02 11:17 UTC, jean-michel-perli-sonsin commented on src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
>       * Checks that the [decodedMessages] contains exact one message and its raw data is the same as [originalData].
```suggestion
     * Checks that the [decodedMessages] contains exactly one message and its raw data is the same as [originalData].
```

2021-06-02 11:28 UTC, jean-michel-perli-sonsin requested changes
Hello, please see if you agree with the suggestions proposed below:
README.md
Line 219/232 - Update sailfish-utils to fix **a** problem with message names

Line 228/241 - **Allows** the codec **to produce** more than one message during decoding

src/main/kotlin/com/exactpro/th2/codec/AbstractSyncCodec.kt
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/CodecException.kt 
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
Line 101/118 - // should never happen here because we **checked** it earlier

src/main/kotlin/com/exactpro/th2/codec/EncodeProcessor.kt 
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/Main.kt
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/MessageProcessor.kt
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/SyncDecoder.kt 
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/SyncEncoder.kt 
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/configuration/ApplicationContext.kt
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/configuration/Configuration.kt
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

src/test/kotlin/com/exactpro/th2/codec/configuration/TestApplicationContext.kt 
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

The rest of the text as well as the other comments were ok.

Thanks!

2021-06-02 13:12 UTC, IvanChadin commented
> Hello, please see if you agree with the suggestions proposed below:
> README.md
> Line 219/232 - Update sailfish-utils to fix **a** problem with message names
> 
> Line 228/241 - **Allows** the codec **to produce** more than one message during decoding
> 
> src/main/kotlin/com/exactpro/th2/codec/AbstractSyncCodec.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/CodecException.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
> Line 101/118 - // should never happen here because we **checked** it earlier
> 
> src/main/kotlin/com/exactpro/th2/codec/EncodeProcessor.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/Main.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/MessageProcessor.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/SyncDecoder.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/SyncEncoder.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/configuration/ApplicationContext.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/configuration/Configuration.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> src/test/kotlin/com/exactpro/th2/codec/configuration/TestApplicationContext.kt
> Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)
> 
> The rest of the text as well as the other comments were ok.
> 
> Thanks!

Done

2021-06-02 13:16 UTC, jean-michel-perli-sonsin submitted a review, later dismissed

2021-06-11 16:31 UTC, OptimumOpium requested changes
Also, please take a look at comments for V2 version
https://github.com/th2-net/th2-codec-sailfish/pull/14

2021-06-11 16:31 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/AbstractSyncCodec.kt
> +            } catch (exception: RuntimeException) {
We should use Exception instead of RuntimeException, I think

2021-06-11 16:31 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
> +     * Checks that the [decodedMessages] contains exactly one message and its raw data is the same as [originalData].
This method does not check that the decoding result is a single message anymore

2021-07-13 10:28 UTC, OptimumOpium approved these changes

2021-07-13 10:34 UTC, merged