Added extraction of messages from EvolutionBatch when decoding RawMessages
th2-net/th2-codec-sailfish pull request #31
Opened 2021-06-17 06:20 UTC by Max-81

2021-06-17 07:49 UTC, Nikita-Smirnov-Exactpro requested changes

2021-06-17 07:49 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +    + Added extraction of messages from EvolutionBatch when decoding RawMessages
Please information about cases where this change can help

2021-06-17 08:18 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
> +            }
Can be replaced with the following code
```suggestion
            val decodedMessages = getCodec().decode(data, source.toCodecContext())
                            .flatMap {
                              if (msg.name == EvolutionBatch.MESSAGE_NAME) {
                                  EvolutionBatch(msg).batch
                              } else {
                                  listOf(msg)
                              }
                            }
```

2021-06-18 07:41 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-06-18 07:47 UTC, jean-michel-perli-sonsin commented on README.md
> +    + Added extraction of messages from EvolutionBatch when decoding RawMessages. This is necessary if evolutionSupportEnabled mode is true - Sailfish codecs package the decoding results in Evolution
```suggestion
    + Added extraction of messages from EvolutionBatch when decoding RawMessages. This is necessary if evolutionSupportEnabled mode is set to true - Sailfish codecs package the decoding results in EvolutionBatch.
```

2021-06-18 07:49 UTC, jean-michel-perli-sonsin approved these changes
Hi, please see if you agree with the suggestion made.
The rest of the changes are according to the previous comments/suggestions.
Thanks!

2021-06-18 08:14 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-06-18 08:34 UTC, merged