[TH-2013] Message creation on error
th2-net/th2-codec-sailfish pull request #32
Opened 2021-06-21 08:54 UTC by Topru333

2021-06-21 09:12 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
> +                        ex
Do we really need to create a new exception? Why can't we pass the message and the original exception to the method straight away?

2021-06-21 09:12 UTC, OptimumOpium commented on README.md
> +  + Added extraction of messages from EvolutionBatch when decoding RawMessages. This is necessary if evolutionSupportEnabled mode is set to true - Sailfish codecs package the decoding results in Evol
Please, correct the formatting. It is different from other places in file

2021-06-21 12:49 UTC, OptimumOpium requested changes

2021-06-21 12:49 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +    val content = StringBuilder().apply {
You can use `buildString` function instead

2021-06-21 12:49 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .setMessageType("th2-codec-error")
Please, extract message type to a constant

2021-06-21 12:49 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .putProperties("content", content)
Please, extract property name to a constant

2021-06-21 12:49 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +    //val content = exception.getAllMessages()
Remove redundant code

2021-06-21 12:49 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .putAllProperties(metadata.propertiesMap)
There is a `toMessageMetadataBuilder` function in DecodeProcessor that does almost the same.  We probably need to move it to MessageUtil file

2021-06-22 08:38 UTC, Topru333 commented
Wrong act of force pushing, my bad

2021-06-22 08:45 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/DecodeProcessor.kt
> +            logger.error(ex) { "Cannot decode message from $source.\nCreating th2-codec-error message with description." }
Try not to use new line in log messages

2021-06-22 08:45 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .putProperties(ERROR_CONTENT_PROPERTY, content)
Why don't we add the content as a message field? The user won't see any property in the UI. But he will see the fields

2021-06-22 08:45 UTC, OptimumOpium commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .putProperties(ERROR_CONTENT_PROPERTY, content)
@Nikita-Smirnov-Exactpro What do you think?

2021-06-22 09:24 UTC, Topru333 commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .putProperties(ERROR_CONTENT_PROPERTY, content)
Aren't properties supposed to be system side info? Error log is mostly system side information about problem that was acquired

2021-06-23 14:26 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/codec/util/MessageUtil.kt
> +        .putProperties(ERROR_CONTENT_PROPERTY, content)
I aggry with @OptimumOpium the reason for a problem should be visible for a user.

2021-06-24 08:22 UTC, Nikita-Smirnov-Exactpro reviewed
Looks fine for me

2021-06-24 08:22 UTC, Nikita-Smirnov-Exactpro commented on src/test/kotlin/com/exactpro/th2/codec/TestDecodeProcessor.kt
> +        assertEquals("th2-codec-error", builder.metadata.messageType)
Use constant instead of string 
```suggestion
        assertEquals(ERROR_TYPE_MESSAGE, builder.metadata.messageType)
```

2021-06-24 12:05 UTC, OptimumOpium approved these changes

2021-06-24 12:48 UTC, merged